version: "3"

services:
  selenium:
    image: selenium/standalone-chrome-debug:2.48.2
    ports:
      - "5900:5900"
      - "4444:4444"
    networks:
      - default

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - vanguard_db:/data/db

  api:
    build: .
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    networks:
      - default
    environment:
      MONGO_URL: mongodb://mongo:27018

volumes:
  vanguard_db:

networks:
  default:
